name: Xarm
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy>=1.23
  - scipy>=1.9
  - sympy>=1.10
  - pyserial>=3.5
  - setuptools
  - wheel

  - pip:
      - ikpy
      - xarm-python-sdk
      - minimalmodbus
      - pyrobotiqgripper
